version: '3.9'

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=strava
      - DOCKER_INFLUXDB_INIT_BUCKET=strava_bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=90d

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - '3000:3000'
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123

  api:
    build: .
    container_name: strava_api
    ports:
      - '8000:8000'
    depends_on:
      - influxdb
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_ORG=strava
      - INFLUX_BUCKET=strava_bucket
      - INFLUX_TOKEN=admin123
      - STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}
    volumes:
      - ./tokens.json:/app/tokens.json
      - ./last_sync.json:/app/last_sync.json

volumes:
  influxdb_data:
